version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - rabbit

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - rabbit

  db:
    image: mongo
    ports:
      - "27017:27017"

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
